spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      url: redis://default:redispw@localhost:55000
file:
  path: /Users/chungsanghwa/projects/images/ShinChekBang/