spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
file:
  path: /Users/chungsanghwa/projects/images/ShinChekBang/