spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/shinchekbang?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldj
    password: ${MYSQL_PW}
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
api:
  tosspayments:
    secret: ${TOSS_PG_SECRET}