spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
  mvc:
    hiddenmethod:
      filter:
        enabled: true
api:
  tosspayments:
    secret: ${TOSS_PG_SECRET}